apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kc2ikarni-java-springboot-gitops-repository
spec:
  url: https://github.com/rhopp-rhtap-testing/kc2ikarni-java-springboot-gitops